version: "3.3"

services:
        mongodb-dev:
                image: mongo
                ports:
                        - "27017:27017"
                networks:
                        - advance_cache_network

                volumes:
                        - "~/repo/docker/mongo/mongodb_data:/data/db"

        postgresql-dev:
                image: postgres
                ports:
                        - "5432:5432"
                networks:
                        - advance_cache_network

                volumes:
#                        - "~/repo/docker/postgresql/postgres_data:/var/lib/postgresql/data"
                        # Let's us to run sql scripts after docker database start
                        - "./sql_scripts:/docker-entrypoint-initdb.d"

networks:
        advance_cache_network:
                driver: bridge
